name: Create and publish a package
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: npm install
              run: |
                  yarn install
                  yarn build
            # - uses: actions/upload-artifact@main
            #   with:
            #       name: webpack artifacts
            #       path: public/

    build-and-push-image:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Log in to GitHub Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Install dependencies
              run: |
                  yarn install
            - name: Build application
              run: |
                  yarn build
            - name: Exclude dev-only dependencies
              run: |
                  yarn install --production
            - name: Build docker image
              run: |
                  docker build \
                    -t docker.pkg.github.com/${{ github.repository }}/app:${{ github.sha }} \
                    -t docker.pkg.github.com/${{ github.repository }}/app:latest \
                    .
            - name: Dry run application
              run: |
                  docker run -e DRY_RUN=true docker.pkg.github.com/${{ github.repository }}/app:${{ github.sha }}
            - name: Push docker image to Github Package Registry
              run: |
                  docker push docker.pkg.github.com/${{ github.repository }}/app
